- crisischeckin/Models/Migrations/DefaultData.sql.txt
As a new contributor I followed the steps in the Contributing.md file but received errors while running the DefaultData.sql.txt script. 
The errors were due to a new field <code>PersonIsCheckedIn</code> on the <code>Commitment</code> table which was defined as <code>Not Nullable</code> but was not being populated by the script.
I've updated the script to set this flag to 'true' in all instances.
There is another new <code>int</code> field on the <code>Commitment</code> table, <code>Status</code>, but this will default to 0 so no additional data is required for the script to run successfully.
> Updated data seeding script to reflect current database schema (resubmitted due to user error!)

- crisischeckin/Models/Disaster.cs
- crisischeckin/Services.UnitTest/DisasterServiceTest.cs
- crisischeckin/Services/DataService.cs
- crisischeckin/Services/DisasterService.cs
- crisischeckin/Services/Exceptions/DisasterNotFoundException.cs
- crisischeckin/Services/Interfaces/IDataService.cs
- crisischeckin/Services/Interfaces/IDisaster.cs
- crisischeckin/Services/Services.csproj
- crisischeckin/crisicheckinweb/Controllers/DisasterController.cs
- crisischeckin/crisicheckinweb/Views/Disaster/Create.cshtml
Actual data update performed by DataService. Update method check for duplicate disaster name refined and  now returns the updated object with exceptions thrown as appropriate.
Unit tests added for valid and invalid operations
> Issue #224 - Updated behaviour inline with VolunteerService

- crisischeckin/Services.UnitTest/AdminServiceTests.cs
- crisischeckin/Services.UnitTest/MessageServiceTests.cs
- crisischeckin/Services/AdminService.cs
- crisischeckin/Services/Interfaces/IAdmin.cs
- crisischeckin/Services/MessageService.cs
- crisischeckin/Services/RecipientCriterion.cs
- crisischeckin/crisicheckinweb/Controllers/VolunteerController.cs
- crisischeckin/crisicheckinweb/ViewModels/SendMessageToAllVolunteersByDisasterViewModel.cs
- crisischeckin/crisicheckinweb/Views/Volunteer/CreateMessage.cshtml
Cleans up the send mail UI a bit, and adds a checkbox to send to only Cluster Coordinators.
Let me know about the approach in the AdminService?  Should I add the new method publically to IAdmin instead of doing it conditionally?
> Allow emails to be sent only to cluster coordinators

- crisischeckin/crisicheckinweb/Views/Volunteer/CreateMessage.cshtml
When the message length exceeds 600 characters, have a client side
warning about the message length. Resolves issue #175.
> Give immediate feedback about message length

- crisischeckin/Services/SmtpMessageSender.cs
- crisischeckin/crisicheckinweb/App_Start/NinjectWebCommon.cs
As discussed in https://github.com/HTBox/crisischeckin/pull/241#issuecomment-74406785
I moved construction and configuration of the SmtpClient to the Ninject
Container registration instead of creating a new SmtpClient in the
SmtpMessageSender.
fixes HTBox/crisischeckin#243
> Use injected SmtpClient factory instead of default constructor.

- crisischeckin/crisicheckinweb/Controllers/HomeController.cs
The cluster coordinators were not shown in the list of commitments when
the user belonged to a cluster other than id 1.
Fixes HTBox/crisischeckin#248
> Use the cluster id of the user when fetching the cluster coordinators.

- crisischeckin/crisicheckinweb/ViewModels/VolunteerViewModel.cs
When not filling in the fields on the volunteer form, error messages for all fields are generated by using the property name (StartDate) instead of a more user friendly text with spaces (Start Date).
Fixes HTBox/crisischeckin#42
> Added DisplayName to VolunteerViewModel to generate user friendly errors.

- crisischeckin/crisicheckinweb/Views/Shared/_Layout.cshtml
Added inclusion of bootstrap.min.js so that the responsive menu opens when clicked on.
(also removed protocol from jquery cdn include so that the https version is used when deployed)
Fixes HTBox/crisischeckin#188
> Bootstrap.js was not included so the 'responsive' menu didn't work.

- crisischeckin/Services.UnitTest/AdminServiceTests.cs
- crisischeckin/Services.UnitTest/MessageServiceTests.cs
- crisischeckin/Services/AdminService.cs
- crisischeckin/Services/Interfaces/IAdmin.cs
- crisischeckin/Services/MessageService.cs
- crisischeckin/Services/RecipientCriterion.cs
- crisischeckin/WebProjectTests/VolunteerControllerTests.cs
- crisischeckin/crisicheckinweb/Controllers/VolunteerController.cs
- crisischeckin/crisicheckinweb/ViewModels/SendMessageToAllVolunteersByDisasterViewModel.cs
- crisischeckin/crisicheckinweb/Views/Volunteer/CreateMessage.cshtml
All public methods on the AdminService to retrieve volunteers now have an optional checkedInOnly parameter (defaults to false) for filtering.
Fixes HTBox/crisischeckin#10
> Added 'Send to checked-in volunteers only' checkbox to Send Message form

- crisischeckin/Services.UnitTest/DisasterServiceTest.cs
- crisischeckin/Services/DisasterService.cs
- crisischeckin/crisicheckinweb/Controllers/HomeController.cs
- crisischeckin/crisicheckinweb/ViewModels/VolunteerViewModel.cs
Changed the error message when the selected start date is before today to be more precise and moved this comparison to the viewmodel. By implementing the IValidatableObject the throwing new ArgumentException can be removed from the controller.
Fixes HTBox/crisischeckin#179
> Changed error message and moved date comparisons for model validation.

- crisischeckin/Services.UnitTest/ClusterCoordinatorService/GetClusterCoordinatorTests.cs
- crisischeckin/Services/ClusterCoordinatorService.cs
For now the persons are only filtered by disaster (as filtering by selected cluster would need more complex javascript code for client filtering or for making extra ajax requests to fetch the filtered people based on the selected cluster).
Fixes HTBox/crisischeckin#259
> Filter the persons on disaster when assigning a cluster coordinator.

- crisischeckin/crisicheckinweb/ViewModels/RegisterModel.cs
- crisischeckin/crisicheckinweb/scripts/App/accountRegister.js
Delayed the check for availability of a username until three characters are typed to prevent a message that the username is available when only one or two characters are filled in.
The DataAnnotations on the viewmodel to check for the length of username were on the private field instead of the public property so they were never used.
Fixes HTBox/crisischeckin#177
> Fixed validation for User name when registering.

- crisischeckin/WebProjectTests/HomeControllerTests.cs
- crisischeckin/WebProjectTests/Infrastructure/PasswordComplexityTests.cs
- crisischeckin/WebProjectTests/WebProjectTests.csproj
- crisischeckin/crisicheckinweb/App_GlobalResources/DefaultErrorMessages.Designer.cs
- crisischeckin/crisicheckinweb/App_GlobalResources/DefaultErrorMessages.resx
- crisischeckin/crisicheckinweb/Controllers/AccountController.cs
- crisischeckin/crisicheckinweb/Infrastructure/Attributes/BasicPasswordAttribute.cs
- crisischeckin/crisicheckinweb/Infrastructure/PasswordComplexity.cs
- crisischeckin/crisicheckinweb/crisicheckinweb.csproj
By moving the password complexity check to a separate class it can be used by both the BasicPasswordAttribute and the AccountController.
Extra password checks can be added to the PasswordComplexity class when needed.
Fixes HTBox/crisischeckin#45
> Moved Password complexity check to separate class; added check username != password.

- crisischeckin/crisicheckinweb/Controllers/AccountController.cs
- crisischeckin/crisicheckinweb/Controllers/DisasterController.cs
- crisischeckin/crisicheckinweb/Controllers/HomeController.cs
- crisischeckin/crisicheckinweb/Filters/AccessDeniedAuthorizeAttribute.cs
- crisischeckin/crisicheckinweb/Infrastructure/Attributes/AccessDeniedAuthorizeAttribute.cs
- crisischeckin/crisicheckinweb/Views/Home/AccessDenied.cshtml
- crisischeckin/crisicheckinweb/crisicheckinweb.csproj
When current user is logged in but not authorized for an admin action the application should redirect to an access denied page instead of showing another login form.
Fixes HTBox/crisischeckin#50
> Added AccesDeniedAuthorizeAttribute for redirecting when not in role.

- crisischeckin/crisicheckinweb/App_Start/BundleConfig.cs
- crisischeckin/crisicheckinweb/Views/Shared/_Layout.cshtml
This happens only in release mode.
Solved by creating a separate bundle for jquery ui theme.
> List by Disaster page renders calendar incorrectly because of bundling.

- crisischeckin/WebProjectTests/AccountControllerTests.cs
- crisischeckin/crisicheckinweb/Controllers/AccountController.cs
- crisischeckin/crisicheckinweb/Views/Account/ConfirmAccount.cshtml
- crisischeckin/crisicheckinweb/Views/Account/RegistrationSuccessful.cshtml
- crisischeckin/crisicheckinweb/Wrappers/IWebSecurityWrapper.cs
- crisischeckin/crisicheckinweb/Wrappers/UserNotActivatedException.cs
- crisischeckin/crisicheckinweb/Wrappers/WebSecurityWrapper.cs
- crisischeckin/crisicheckinweb/crisicheckinweb.csproj
Email with confirmation link is sent after a user registration. 
The user cannot login before the link is clicked (or copied in the browser) and the account is activated.
Fixes HTbox/crisischeckin#46
> Implemented Account activation functionality.

- crisischeckin/Services/ClusterCoordinatorService.cs
- crisischeckin/crisicheckinweb/Controllers/ClusterCoordinatorController.cs
- crisischeckin/crisicheckinweb/Views/ClusterCoordinator/AssignCoordinator.cshtml
By passing the current disasterId as a parameter for the action we can redirect to the disaster page.
Also did some minor code cleanup.
Fixes HTBox/crisischeckin#195
> Backbutton after unassigning coordinator resulted in wrong redirect.

- crisischeckin/Models/Cluster.cs
- crisischeckin/Models/ClusterCoordinatorLog.cs
- crisischeckin/Models/CrisisCheckin.cs
- crisischeckin/Models/Disaster.cs
- crisischeckin/Models/Person.cs
- crisischeckin/Models/User.cs
- crisischeckin/crisicheckinweb/ViewModels/ClusterCoordinatorViewModel.cs
- crisischeckin/crisicheckinweb/ViewModels/ClusterViewModel.cs
- crisischeckin/crisicheckinweb/ViewModels/DisasterViewModel.cs
- crisischeckin/crisicheckinweb/ViewModels/ForgotPasswordViewModel.cs
- crisischeckin/crisicheckinweb/ViewModels/LoginModel.cs
- crisischeckin/crisicheckinweb/ViewModels/RegisterModel.cs
- crisischeckin/crisicheckinweb/ViewModels/SendMessageToAllVolunteersByDisasterViewModel.cs
- crisischeckin/crisicheckinweb/ViewModels/UnassignClusterCoordinatorViewModel.cs
In addition to solving issue #59 this will also cover some other free-form entry fields. Names for humans allow for 30 character first names and 30 character last names. Names for things (i.e. disasters, clusters, etc) are 50 characters. 
In order to maintain the flexibility on the DB side for future expansion, I removed the StringLengthAttributeConvention from the DBContext.
> Added Length Constraints Free-Form Inputs

- Contributing.md
`Update-Database` will fail without a patched `EntityFramework.psm1` file.
The solution for the issue I raised:  https://github.com/HTBox/crisischeckin/issues/287
> Added instructions for solving Visual Studio 2015 bug. 

- crisischeckin/AcceptanceTests/AcceptanceTests.csproj
- crisischeckin/Common/Common.csproj
- crisischeckin/Common/Constants.cs
- crisischeckin/CrisisCheckinWeb.sln
- crisischeckin/Models/Models.csproj
- crisischeckin/Services.UnitTest/Services.UnitTest.csproj
- crisischeckin/Services/Services.csproj
- crisischeckin/Services/SmtpMessageSender.cs
- crisischeckin/Services/SubjectEnrichmentService.cs
- crisischeckin/WebProjectTests/WebProjectTests.csproj
- crisischeckin/crisicheckinweb/App_Start/NinjectWebCommon.cs
- crisischeckin/crisicheckinweb/Properties/PublishProfiles/LocalStaging.pubxml
- crisischeckin/crisicheckinweb/Web.Release.config
- crisischeckin/crisicheckinweb/Web.Staging.config
- crisischeckin/crisicheckinweb/Web.config
- crisischeckin/crisicheckinweb/crisicheckinweb.csproj
This pull request centers around:
- **New web.config transforms and publish settings for Staging**.
- Introduced of a new **environment app setting**, and some constants to help prevent magic strings. Which seemed to be the convention in this project. 
- **SubjectEnrichmentService**, which prepends environment tags to non-production mail subjects. 
Notes:
I didn't want to make assumptions about how configuration should be handled so I just did this with ConfigurationManager to start. It's not too hard to go back and add a facade for testing purposes, etc. 
For this initial approach, I did have to add System.Configuration to Services. I also referenced Common since I added a few constants and needed to use them. I wasn't sure why that was not already referenced. Let me know if I should …
> Updated mail behavior for staging and development #286

- crisischeckin/crisicheckinweb/Views/Home/Index.cshtml
Defect #398: In the Commitment for today section, there should be separators between the fields names and values selected
> Added separators to improve readability

- crisischeckin/crisicheckinweb/Views/Cluster/List.cshtml
Fixes issue #401.
Tested in Firefox 31, Chrome 47 and IE8.  In any browser that does show a page after a cluster is deleted and the Back button is clicked, the page now re-retrieves the most up-to-date list of clusters from the server instead of showing the now-obsolete list from the browser cache.  This prevents the user from subsequently trying to re-delete the phantom cluster.
> Added cache-control header to Cluster List page so it's always right

- crisischeckin/crisicheckinweb/Views/ClusterCoordinator/Index.cshtml
When allocating cluster coordinators, it was felt that the ui was confusing when there was no person available. 
In those circumstances, I now show a simple statement that noone is available instead of showing the (allegedly) confusing drop down...
> Don't show an empty dropdown on Cluster Coordinator Allocation

- crisischeckin/crisicheckinweb/Views/Account/Login.cshtml
- crisischeckin/crisicheckinweb/Views/Shared/_LoginLayout.cshtml
Added new layout page for login.  This layout page contains a navbar that only has the CrisisCheckin Logo.
> Issue #606 - "View CheckIns" link doesn't work prior to logging in

- crisischeckin/crisicheckinweb/Views/Shared/_AdminLayout.cshtml
- crisischeckin/crisicheckinweb/Views/Shared/_VolunteerLayout.cshtml
- crisischeckin/crisicheckinweb/Views/Volunteer/ListByDisaster.cshtml
- crisischeckin/crisicheckinweb/Views/Volunteer/ListResourceCheckinsByDisaster.cshtml
Both the Admin and Volunteer UIs shared the Field Reported Data and Checkins pages.  However, both these pages used _VolunteerLayout.cshtml. Therefore, when an Admin clicked links to either of those pages in the NavBar, _VolunteerLayout.cshtml was loaded and not _AdminLayout.cshtml.  The result was that the NavBar would always change to what the Volunteer would see. 
By adding some logic to check whether the user had the Admin role in the Field Reported Data and Checkins pages, the appropriate layout pages for both volunteers and admins are loaded.
I also removed 'View' in the NavBar links.  In my opinion, it is obvious that when you click "Checkins" in the NavBar, you are going to see the Checkins. In addition, the word 'View' in front of each link was beginning to take up too much space …
> Cleaned up Navbar

- crisischeckin/crisicheckinweb/ViewModels/NewOrganizationViewModel.cs
- crisischeckin/crisicheckinweb/Views/Home/Index.cshtml
Fixes #695.
Button located on volunteer homepage following discussion found on [https://github.com/HTBox/crisischeckin/pull/537](url)
> Adding 'add new organization link' to volunteer homepage.

- README.md
markdown requires a space after the hashmarks.  This fixes the rendering to actually be headers.  Also added "Step1" prefix to "a.", "b.", etc, subheaders so they made more sense in the page flow.
> Fixing markdown for "step" headers
