HTBox/crisischeckin

crisischeckin/crisicheckinweb/Views/Home/Index.cshtml

Added volunteer form to table. Swapped table positions. Fixed icon on
remove button. added text to remove button.

Home page UI fixes

---

crisischeckin/crisicheckinweb/Views/ClusterCoordinator/AssignCoordinator.cshtml
crisischeckin/crisicheckinweb/Views/Home/Index.cshtml

changed icon-remove to "glyphicon glyphicon-remove"

Fix for Issue #206

---

crisischeckin/crisicheckinweb/Views/ClusterCoordinator/AssignCoordinator.cshtml
crisischeckin/crisicheckinweb/Views/ClusterCoordinator/Index.cshtml

Cluster Coordinatior UI changes - Improved page for various screen sizes. Made table more readable. Changed button color for consistency with other pages.

UI updates for Cluster Coordination

---

crisischeckin/Services.UnitTest/ClusterCoordinatorService/GetClusterCoordinatorTests.cs
crisischeckin/Services/ClusterCoordinatorService.cs
crisischeckin/Services/Interfaces/IClusterCoordinatorService.cs
crisischeckin/WebProjectTests/HomeControllerTests.cs
crisischeckin/crisicheckinweb/Controllers/HomeController.cs
crisischeckin/crisicheckinweb/ViewModels/VolunteerViewModel.cs
crisischeckin/crisicheckinweb/Views/Home/Index.cshtml

Instead of an empty "My Commitments" table, volunteers will see a thank
you message and some instructions.

Thank you for volunteering message

---

crisischeckin/Models/Commitment.cs
crisischeckin/Models/CrisisCheckin.cs
crisischeckin/Models/Models.csproj
crisischeckin/Models/VolunteerType.cs
crisischeckin/Services.UnitTest/DisasterServiceTest.cs
crisischeckin/Services/DataService.cs
crisischeckin/Services/DisasterService.cs
crisischeckin/Services/Interfaces/IDataService.cs
crisischeckin/Services/Interfaces/IDisaster.cs
crisischeckin/Services/Interfaces/IVolunteerTypeService.cs
crisischeckin/Services/Services.csproj
crisischeckin/Services/VolunteerTypeService.cs
crisischeckin/WebProjectTests/HomeControllerTests.cs
crisischeckin/crisicheckinweb/App_Start/DbConfig.cs
crisischeckin/crisicheckinweb/App_Start/NinjectWebCommon.cs
crisischeckin/crisicheckinweb/Controllers/HomeController.cs
crisischeckin/crisicheckinweb/ViewModels/VolunteerViewModel.cs
crisischeckin/crisicheckinweb/Views/Home/Index.cshtml
crisischeckin/crisicheckinweb/Web.config

Volunteers can now create local or remote volunteer commitments.

Support creating Local or Remote Volunteers

---

crisischeckin/crisicheckinweb/App_Start/DbConfig.cs
crisischeckin/crisicheckinweb/Content/htbox-theme.css
crisischeckin/crisicheckinweb/Views/Shared/_AdminLayout.cshtml
crisischeckin/crisicheckinweb/Views/Shared/_Layout.cshtml
crisischeckin/crisicheckinweb/Views/Shared/_LoginStatus.cshtml
crisischeckin/crisicheckinweb/Views/Shared/_VolunteerLayout.cshtml
crisischeckin/crisicheckinweb/crisicheckinweb.csproj

Made the navbar the same red and white as the navbar on htbox.org

Added HTBox theme

---

crisischeckin/crisicheckinweb/Views/Home/Index.cshtml

Label accidently got copied with the drop down. Column is already
labeled as "location". Extra label as been dealt with...

Removed extra volunteer type label

---

crisischeckin/crisicheckinweb/Views/Disaster/Create.cshtml
crisischeckin/crisicheckinweb/Views/Disaster/List.cshtml

UI improvement with bootstrap on disaster screens

Disaster UI improvement

---

crisischeckin/crisicheckinweb/Content/htbox-theme.css
crisischeckin/crisicheckinweb/Views/ClusterCoordinator/AssignCoordinator.cshtml
crisischeckin/crisicheckinweb/Views/ClusterCoordinator/Index.cshtml
crisischeckin/crisicheckinweb/Views/Disaster/List.cshtml
crisischeckin/crisicheckinweb/Views/Home/Index.cshtml
crisischeckin/crisicheckinweb/Views/Volunteer/ListByDisaster.cshtml

Theme changes to look more like the theme on htbox.org

Theme changes

---

crisischeckin/Services/MessageCoordinator.cs
crisischeckin/Services/SmtpMessageSender.cs
crisischeckin/crisicheckinweb/App_Start/DbConfig.cs
crisischeckin/crisicheckinweb/Properties/PublishProfiles/LocalRelease.pubxml
crisischeckin/crisicheckinweb/Web.Release.config
crisischeckin/crisicheckinweb/Web.config
crisischeckin/crisicheckinweb/crisicheckinweb.csproj

In response to Issue #235. I've changed Web.config and
Web.Release.config to have SmtpMessageSender.SendMessage drop emails
into C:\Users\[USER]\AppData\Roaming while developing and send via smtp
server when in release mode.

Send emails to directory during development

---

crisischeckin/crisicheckinweb/Controllers/ClusterCoordinatorController.cs

fixes HTBox/crisischeckin#168 (ClusterCoordinator views were accessible and editable without logging in).

Changed base class of ClusterCoordinatorController to enable authorization.

---

crisischeckin/crisicheckinweb/Views/Shared/_Layout.cshtml

- Formatted the code
- Changed the version of jquery included in the page to match the project files version, from 1.9.1 to 2.1.1;
- The other problems mentioned in the issue were already fixed

Fix for issue 173

---

crisischeckin/crisicheckinweb/Content/Forms.css
crisischeckin/crisicheckinweb/Content/Forms.min.css
crisischeckin/crisicheckinweb/Views/Account/ChangeContactInfo.cshtml
crisischeckin/crisicheckinweb/Views/Account/ChangePassword.cshtml
crisischeckin/crisicheckinweb/Views/Account/Login.cshtml
crisischeckin/crisicheckinweb/Views/Account/Register.cshtml
crisischeckin/crisicheckinweb/Views/Volunteer/CreateMessage.cshtml

Introduced new CSS class 'required' (showing a red asterisk after the label of a required field) and applied it to all required fields in all forms in the application.
Fixes HTBox/crisischeckin#26

Added 'required' CSS class, applied to all required input fields.

---

crisischeckin/AcceptanceTests/With_an_empty_database_environment.cs

When running all tests in the solution two acceptance tests were marked as failing. I made them pass again.

Repaired broken acceptance tests.

---

crisischeckin/WebProjectTests/AccountControllerTests.cs
crisischeckin/WebProjectTests/DisasterControllerTests.cs
crisischeckin/WebProjectTests/HomeControllerTests.cs
crisischeckin/WebProjectTests/VolunteerControllerTests.cs
crisischeckin/crisicheckinweb/Api/EntitiesController.cs
crisischeckin/crisicheckinweb/Controllers/AccountController.cs
crisischeckin/crisicheckinweb/Controllers/HomeController.cs
crisischeckin/crisicheckinweb/Wrappers/IWebSecurityWrapper.cs
crisischeckin/crisicheckinweb/Wrappers/UserCreationException.cs
crisischeckin/crisicheckinweb/Wrappers/WebSecurityWrapper.cs
crisischeckin/crisicheckinweb/crisicheckinweb.csproj

Only some of the WebSecurity methods were wrapped. I wrapped the rest and all calls to Roles, Membership and controller.User to make future testing more easy.
I also did some cleanup/refactoring of the existing controller tests and added extra unit tests for the AccountController.Register action.

Wrapped missing WebSecurity, Roles and Membership methods to make code more testable (2).

---

crisischeckin/WebProjectTests/AccountControllerTests.cs
crisischeckin/crisicheckinweb/App_Start/NinjectWebCommon.cs
crisischeckin/crisicheckinweb/Controllers/AccountController.cs
crisischeckin/crisicheckinweb/Infrastructure/IPasswordResetSender.cs
crisischeckin/crisicheckinweb/Infrastructure/PasswordResetSender.cs
crisischeckin/crisicheckinweb/ViewModels/ForgotPasswordViewModel.cs
crisischeckin/crisicheckinweb/ViewModels/ResetPasswordViewModel.cs
crisischeckin/crisicheckinweb/Views/Account/ForgotPassword.cshtml
crisischeckin/crisicheckinweb/Views/Account/Login.cshtml
crisischeckin/crisicheckinweb/Views/Account/PasswordResetCompleted.cshtml
crisischeckin/crisicheckinweb/Views/Account/PasswordResetRequested.cshtml
crisischeckin/crisicheckinweb/Views/Account/ResetPassword.cshtml
crisischeckin/crisicheckinweb/Wrappers/IWebSecurityWrapper.cs
crisischeckin/crisicheckinweb/Wrappers/WebSecurityWrapper.cs
crisischeckin/crisicheckinweb/crisicheckinweb.csproj

Implemented password rest functionality by adding a ForgotPassword page where the user can give his username. He will receive an email with a link (token) to reset his password via the ResetPassword page.
The sending of the email should be refactored to use the Services.MessageSender as soon as that issue is completed.
This PR will fix issue #187 (but as there are additional questions/comments in that issue, I'm not sure if it will be enough to close it).

Implementation of Password Reset functionality.

---

crisischeckin/crisicheckinweb/Controllers/AccountController.cs
crisischeckin/crisicheckinweb/Views/Account/ChangePassword.cshtml
crisischeckin/crisicheckinweb/Views/Account/Register.cshtml
crisischeckin/crisicheckinweb/Views/Account/ResetPassword.cshtml
crisischeckin/crisicheckinweb/crisicheckinweb.csproj
crisischeckin/crisicheckinweb/scripts/App/changePassword.js

Implemented on Registration, Password Reset and Change Password page.
Fixes HTBox/crisischeckin#196

Immediate password validation feedback on password input fields

---

crisischeckin/Services/Interfaces/IVolunteerService.cs
crisischeckin/Services/VolunteerService.cs
crisischeckin/WebProjectTests/AccountControllerTests.cs
crisischeckin/crisicheckinweb/Controllers/AccountController.cs
crisischeckin/crisicheckinweb/ViewModels/ForgotPasswordViewModel.cs
crisischeckin/crisicheckinweb/ViewModels/LoginModel.cs
crisischeckin/crisicheckinweb/Views/Account/ForgotPassword.cshtml
crisischeckin/crisicheckinweb/Views/Account/Login.cshtml

Allow login and password reset both by username and by email.

---

crisischeckin/Models/Disaster.cs
crisischeckin/WebProjectTests/DisasterControllerTests.cs
crisischeckin/crisicheckinweb/Controllers/DisasterController.cs
crisischeckin/crisicheckinweb/ViewModels/DisasterViewModel.cs
crisischeckin/crisicheckinweb/Views/Disaster/Create.cshtml
crisischeckin/crisicheckinweb/Views/Disaster/List.cshtml
crisischeckin/crisicheckinweb/crisicheckinweb.csproj

Introduced DisasterViewModel for the consistence with other pages and put DataAnnotations attributes on the Name property.
Fixes HTBox/crisischeckin#34

Restricted the Disaster name to 100 characters.

---

crisischeckin/AcceptanceTests/AcceptanceTests.csproj
crisischeckin/AcceptanceTests/ClusterCoordinatorFeature/A_person_can_be_assigned_as_a_cluster_coordinator_for_a_disaster.cs
crisischeckin/AcceptanceTests/ClusterCoordinatorFeature/A_person_can_be_unassigned_as_a_cluster_coordinator_for_a_disaster.cs
crisischeckin/AcceptanceTests/ClusterCoordinatorFeature/Can_access_person.cs
crisischeckin/AcceptanceTests/With_an_empty_database_environment.cs
crisischeckin/AcceptanceTests/packages.config
crisischeckin/Services.UnitTest/AdminServiceTests.cs
crisischeckin/Services.UnitTest/ClusterCoordinatorService/AssignClusterCoordinatorTests.cs
crisischeckin/Services.UnitTest/ClusterCoordinatorService/GetClusterCoordinatorTests.cs
crisischeckin/Services.UnitTest/ClusterCoordinatorService/GetClusterCoordinatorsTests.cs
crisischeckin/Services.UnitTest/ClusterCoordinatorService/UnassignClusterCoordinatorTests.cs
crisischeckin/Services.UnitTest/DisasterServiceTest.cs
crisischeckin/Services.UnitTest/MessageCoordinatorTest.cs
crisischeckin/Services.UnitTest/MessageServiceTests.cs
crisischeckin/Services.UnitTest/Services.UnitTest.csproj
crisischeckin/Services.UnitTest/VolunteerServiceTest.cs
crisischeckin/Services.UnitTest/packages.config

As mentioned in PR #211, the tests will be converted to NUnit. 
To keep this PR easy to merge I converted only the AcceptanceTests and Services.UnitTest project (the other project will come later this week).

Converted AcceptanceTests and Services.UnitTest projects to NUnit.

---

crisischeckin/WebProjectTests/AccountControllerTests.cs
crisischeckin/WebProjectTests/DisasterControllerTests.cs
crisischeckin/WebProjectTests/HomeControllerTests.cs
crisischeckin/WebProjectTests/Infrastructure/Attributes/BasicPasswordAttributeTests.cs
crisischeckin/WebProjectTests/Infrastructure/PasswordComplexityTests.cs
crisischeckin/WebProjectTests/VolunteerControllerTests.cs
crisischeckin/WebProjectTests/WebProjectTests.csproj
crisischeckin/WebProjectTests/packages.config
crisischeckin/crisicheckinweb/Controllers/AccountController.cs
crisischeckin/crisicheckinweb/Views/Account/ConfirmAccount.cshtml
crisischeckin/crisicheckinweb/Views/Account/RegistrationSuccessful.cshtml
crisischeckin/crisicheckinweb/Wrappers/IWebSecurityWrapper.cs
crisischeckin/crisicheckinweb/Wrappers/UserNotActivatedException.cs
crisischeckin/crisicheckinweb/Wrappers/WebSecurityWrapper.cs
crisischeckin/crisicheckinweb/crisicheckinweb.csproj

Please merge **after** PR #278 to prevent merge conflicts (I used that branch as base for this change).

Converted WebProjectTests project to NUnit.

---

crisischeckin/Models/Commitment.cs
crisischeckin/Services/DataService.cs
crisischeckin/Services/Exceptions/CommitmentNotFoundException.cs
crisischeckin/Services/Interfaces/IDataService.cs
crisischeckin/Services/Interfaces/IVolunteerService.cs
crisischeckin/Services/Services.csproj
crisischeckin/Services/VolunteerService.cs
crisischeckin/WebProjectTests/HomeControllerTests.cs
crisischeckin/crisicheckinweb/Controllers/HomeController.cs
crisischeckin/crisicheckinweb/Views/Home/Index.cshtml
crisischeckin/crisicheckinweb/crisicheckinweb.csproj

I added basic check-in/check-out functionality. It's not feature complete yet (statuses like delayed and unavailable are still missing).

Added check-in/check-out functionality to volunteer homepage.

---

crisischeckin/WebProjectTests/HomeControllerTests.cs

Please double check I've got them the correct way around, looking at the history it looks like it's the test that were wrong, rather than the code, however, it's my first viewing of the code base.

Correcting unit tests

---

crisischeckin/AcceptanceTests/App.config
crisischeckin/Common/Constants.cs
crisischeckin/Services/Message.cs
crisischeckin/Services/MessageCoordinator.cs
crisischeckin/Services/MessageRecipient.cs
crisischeckin/Services/MessageService.cs
crisischeckin/Services/Mocks/TwilioRestClientMock.cs
crisischeckin/Services/SMSMessageSender.cs
crisischeckin/Services/Services.csproj
crisischeckin/Services/packages.config
crisischeckin/crisicheckinweb/App_Start/NinjectWebCommon.cs
crisischeckin/crisicheckinweb/Controllers/VolunteerController.cs
crisischeckin/crisicheckinweb/ViewModels/SendMessageToAllVolunteersByDisasterViewModel.cs
crisischeckin/crisicheckinweb/Views/Volunteer/CreateMessage.cshtml
crisischeckin/crisicheckinweb/Web.config
crisischeckin/crisicheckinweb/crisicheckinweb.csproj
crisischeckin/crisicheckinweb/packages.config

The following were the changes made to support these changes:
* I created a new IMessageSender type which will be used for the SMS messages.
* Changes were made to the page /Volunteer/CreateMessage.cshtml to support sending SMS messages.
Additional Changes:
* I changed the connection string from (localdb)\v11.0 to (localdb)\MSSQLLocaldb, since Microsoft is moving away "from the numbering/versioning for the automatic instance and named it MSSQLLocalDB instead of v12.0". quote from: [link to connect.microsoft.com!](https://connect.microsoft.com/SQLServer/feedback/details/845278/sql-server-2014-express-localdb-does-not-create-automatic-instance-v12-0).  Also I don't have v11.0 installed on my computer.   I can always change back if that is preferred.
Additional notes:
* The Twilio …

Resolves #303

---

crisischeckin/Services.UnitTest/MessageServiceTests.cs
crisischeckin/Services/RecipientCriterion.cs
crisischeckin/crisicheckinweb/Controllers/VolunteerController.cs
crisischeckin/crisicheckinweb/ViewModels/SendMessageToAllVolunteersByDisasterViewModel.cs
crisischeckin/crisicheckinweb/Views/Volunteer/CreateMessage.cshtml

Replaced drop-down list with multi-select ListBox control. Changed the Cluster variable (int) to an IEnumerable<int> called ClusterIds to hold the selected cluster ids.

Resolves #299

---

crisischeckin/crisicheckinweb/Controllers/ClusterController.cs
crisischeckin/crisicheckinweb/Controllers/DisasterController.cs
crisischeckin/crisicheckinweb/Views/Cluster/Create.cshtml
crisischeckin/crisicheckinweb/Views/Cluster/List.cshtml
crisischeckin/crisicheckinweb/Views/Disaster/List.cshtml

#326 
#312,
#313 
#309,
#311 
#308 
#310 
That conference stuff

That conference2015

---

README.md

Added instructions for Mac developers to get set up or developers who do not have visual studio.

Added instructions for mac developers to get set up

---

crisischeckin/Services/DisasterService.cs

"a end date" -> "an end date", fixed the grammar mistake

Fixed grammar error in issue #364

---

crisischeckin/Models/Cluster.cs
crisischeckin/Models/ClusterCoordinatorLog.cs
crisischeckin/Models/Disaster.cs
crisischeckin/Models/Person.cs
crisischeckin/Services/DisasterService.cs

Added error message for string length validation.

Fixed issue number 350

---

.gitignore
crisischeckin/crisicheckinweb/Controllers/ClusterController.cs
crisischeckin/crisicheckinweb/scripts/App/accountRegister.js

This request contains 4 commits.  Each one fixing a different issue.
The following are the issues been fixed:
- Need a confirm email field on registration #335
- First and last name requirements should be displayed up front #334
- Cluster name >= 50 characters throws exception. #350
- System allows same cluster name to be created. #345

Fixing issues 335, 334, 350, and 345

---

crisischeckin/crisicheckinweb/Views/Account/Login.cshtml

tab order goes from username to password and username gets auto focus.

Fix for #435

---

crisischeckin/crisicheckinweb/Views/Disaster/Create.cshtml
crisischeckin/crisicheckinweb/Views/Disaster/List.cshtml

A few things to improve the UI of the Disaster create/edit page.

Beautification of disaster create/edit page

---

crisischeckin/crisicheckinweb/Views/Web.config
crisischeckin/crisicheckinweb/Web.config

updated version numbers in web.config files to match mvc razor references

web.config update

---

crisischeckin/AcceptanceTests/App.config
crisischeckin/Services.UnitTest/DisasterServiceTest.cs

This will ensure that our appveyor builds work correctly.

Update stale tests to get all tests passing.

---

crisischeckin/crisicheckinweb/Views/Disaster/Create.cshtml

Moved the Create Disaster button up to above the fold

---

crisischeckin/crisicheckinweb/Content/htbox-theme.css
crisischeckin/crisicheckinweb/Views/Disaster/Create.cshtml
crisischeckin/crisicheckinweb/crisicheckinweb.csproj
crisischeckin/crisicheckinweb/scripts/App/disasterEdit.js

On Create/Edit Disaster page, add a check/uncheck all checkbox

---

crisischeckin/crisicheckinweb/Views/Shared/_VolunteerLayout.cshtml

For issue #384 
I changed one of the layouts to have the same label for the nav item, and I also switched it to use the MenuItem HTML helper.

Changed nav item so it's consistently labeled

---

crisischeckin/crisicheckinweb/crisicheckinweb.csproj

someone slipped in including the db in project when they shouldn't

remove db from project

---

crisischeckin/crisicheckinweb/Views/Home/Index.cshtml
crisischeckin/crisicheckinweb/Views/Volunteer/_FilterResults.cshtml

Renaming tables (as in UI tables, not database tables) as requested in #492 .

Renaming a couple of tables for Issue492

---

Contributing.md

There are two NUnit Test Runners in the extensions list, only one works
to load the tests.

Clarify which NUnit Extension

---

crisischeckin/crisicheckinweb/ViewModels/RegisterModel.cs
crisischeckin/crisicheckinweb/Views/Account/Register.cshtml
crisischeckin/crisicheckinweb/scripts/App/accountRegister.js

Also fixed false positives with other validations on the registration page.

Issue #608 Added a simple phone number validation

---

crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile.Android/Resources/Resource.Designer.cs
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/CrisisCheckinMobile.csproj
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/LoginPage.cs
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/ViewModels/ProfileViewModel.cs
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/Views/ProfileView.xaml
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/Views/ProfileView.xaml.cs
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/Views/TemporaryView.xaml
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/Views/TemporaryView.xaml.cs

This is needed for other users to hook in the work they have been doing and part of issue #653

add flow for user profile page.

---

crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/ApiClient/CrisisCheckInApiClient.cs
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/ApiClient/ICrisisCheckInApi.cs
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/ApiClient/ICrisisCheckInApiClient.cs
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/CrisisCheckinMobile.csproj
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/Models/RequestDto.cs
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/MyRequests.xaml
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/MyRequests.xaml.cs
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/ViewModels/ProfileViewModel.cs

Api request

---

crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/CrisisCheckinMobile.csproj
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/ResourceListPage.cs
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/ResourceViewPage.cs
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/ViewModels/ProfileViewModel.cs
crisischeckin/CrisisCheckinMobile/CrisisCheckinMobile/ViewModels/ResourceListItemViewModel.cs

Added basic list and view pages and linked to the profile view.

Item #656 - Add/View Resources

---

crisischeckin/Services/DataService.cs
crisischeckin/Services/Interfaces/IDataService.cs
crisischeckin/Services/Interfaces/IResource.cs
crisischeckin/Services/ResourceService.cs
crisischeckin/crisicheckinweb/Content/site.css
crisischeckin/crisicheckinweb/Controllers/ResourcesController.cs
crisischeckin/crisicheckinweb/ViewModels/ResourceIndexViewModels.cs
crisischeckin/crisicheckinweb/Views/Resources/VolunteerResourcesIndex.cshtml
crisischeckin/crisicheckinweb/Views/Resources/_VolunteerResourceIndexResults.cshtml
crisischeckin/crisicheckinweb/Views/Shared/_VolunteerLayout.cshtml
crisischeckin/crisicheckinweb/crisicheckinweb.csproj

This pull request provides volunteers with an additional navbar option named 'Resources'.  This new page allows volunteers to select a disaster and optionally a date for which to filter resources.  The date field will filter resources based on their availability.

Issue #503 - Volunteers can view resources by date and disaster.

---

crisischeckin/crisicheckinweb/ViewModels/RequestDetailsViewModel.cs
crisischeckin/crisicheckinweb/Views/Requests/Details.cshtml

 typo fixes

---

crisischeckin/crisicheckinweb/Views/Cluster/Create.cshtml
crisischeckin/crisicheckinweb/Views/ClusterGroup/List.cshtml

text fixes.

---

crisischeckin/crisicheckinweb/Controllers/OrganizationController.cs
crisischeckin/crisicheckinweb/ViewModels/NewOrganizationViewModel.cs
crisischeckin/crisicheckinweb/Views/Home/Index.cshtml

Confirmation email fix

---

crisischeckin/crisicheckinweb/App_Start/DbConfig.cs

Added the OrganizationID and the Organization to the Person so that there is an Organization associated with the TestUser.

Fixes Issue #683

---

crisischeckin/crisicheckinweb/ViewModels/RegisterModel.cs

Added the organization to be [Required] and removed the "can be null" ("?").

Fixes Issue #701

---

crisischeckin/crisicheckinweb/ViewModels/VolunteerViewModel.cs

Added validation via the viewmodel. Returns an error on view if Description is empty

#626 - Added required to description in Volunteer

---

crisischeckin/crisicheckinweb/App_Start/BundleConfig.cs
crisischeckin/crisicheckinweb/Views/Account/Register.cshtml
crisischeckin/crisicheckinweb/Web.config

#704 enabled jquery validation

fixed the issue where organization dropdown error not clearing on account registration page #704

---

crisischeckin/Services/DisasterService.cs

Adding mapping to resource object from homepage.
